name: VoiceLog
options:
  bundleIdPrefix: com.voicelog
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

packages:
  LogCore:
    path: .

targets:
  VoiceLogApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - VoiceLogApp
    dependencies:
      - package: LogCore
        product: LogCore
    settings:
      INFOPLIST_GENERATION_MODE: GeneratedFile
      PRODUCT_BUNDLE_IDENTIFIER: com.voicelog.app
      PRODUCT_NAME: VoiceLog
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      NSMicrophoneUsageDescription: "VoiceLog needs microphone access to record voice entries."
      NSLocationWhenInUseUsageDescription: "VoiceLog uses your location to tag voice entries."

  VoiceLogWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - VoiceLogWatch
    dependencies:
      - package: LogCore
        product: LogCore
    settings:
      INFOPLIST_GENERATION_MODE: GeneratedFile
      PRODUCT_BUNDLE_IDENTIFIER: com.voicelog.app.watchkitapp
      PRODUCT_NAME: VoiceLogWatch
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      NSMicrophoneUsageDescription: "VoiceLog needs microphone access to record voice entries."
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
      INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.voicelog.app
      INFOPLIST_KEY_WKRunsIndependentlyOfCompanionApp: YES

  VoiceLogWatchUITests:
    type: bundle.ui-testing
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - Tests/VoiceLogWatchUITests
    dependencies:
      - target: VoiceLogWatch
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.voicelog.app.watchkitapp.uitests
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
      TEST_TARGET_NAME: VoiceLogWatch

  LogCoreTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Tests/LogCoreTests
    dependencies:
      - package: LogCore
        product: LogCore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.voicelog.logcore-tests
      SWIFT_VERSION: "5.9"
      GENERATE_INFOPLIST_FILE: YES
